---
title: "Data_Gathering"
output: html_document
---

```{r load_lib}
library(nflreadr)
library(tidyr)
library(dplyr)
```

```{r grab_pbp}

# GRAB PBP DATA
data <- load_pbp(2004:2024)

```

```{r filter_data}

# FILTER DATA TO GET DESIRED COLS
subset <- subset(data,
       season_type == "REG" &
       (
         touchdown == 1 |
         (fourth_down_converted == 1 |
         fourth_down_failed == 1) |
         punt_inside_twenty == 1 |
         own_kickoff_recovery == 1 |
         extra_point_attempt == 1 |
         extra_point_result == "good" |
         field_goal_attempt == 1 |
         field_goal_result == "made" |
         return_touchdown == 1 |
         two_point_attempt == 1 |
         two_point_conv_result == "success" |
         pass_touchdown == 1 |
         rush_touchdown == 1 | 
         interception == 1 |
         fumble_lost == 1 |
         safety == 1
       ),
       select = c(
         season,
         game_id,
         home_team,
         away_team,
         home_score,
         away_score,
         season_type,
         posteam,
         defteam,
         fourth_down_failed,
         fourth_down_converted,
         td_team,
         touchdown,
         punt_inside_twenty,
         own_kickoff_recovery,
         extra_point_attempt,
         extra_point_result,
         field_goal_attempt,
         field_goal_result,
         return_touchdown,
         two_point_attempt,
         two_point_conv_result,
         pass_touchdown,
         rush_touchdown,
         interception,
         fumble_lost,
         safety))
```

```{r mutate_cols}

# GRAB SUCCESSES
subset_mutated <- subset %>%
  mutate(
    fourth_down_attempt = (fourth_down_converted == 1 | fourth_down_failed == 1),
    extra_point_good = extra_point_result == "good",
    field_goal_made = field_goal_result == "made",
    two_point_success = two_point_conv_result == "success"
  )

```


```{r summarize}

# SUMMARIZE SUCCESSES
data_summ <- subset_mutated %>%
  group_by(game_id, posteam) %>%
  summarize(
    season = first(season),
    home_team = first(home_team),
    away_team = first(away_team),
    home_score = first(home_score),
    away_score = first(away_score),
    touchdown = sum(touchdown == 1, na.rm = TRUE),
    fourth_down_attempt = sum(fourth_down_attempt == 1, na.rm = TRUE),
    punt_inside_twenty = sum(punt_inside_twenty == 1, na.rm = TRUE),
    own_kickoff_recovery = sum(own_kickoff_recovery == 1, na.rm = TRUE),
    extra_point_good = sum(extra_point_good == 1, na.rm = TRUE),
    field_goal_made = sum(field_goal_made == 1, na.rm = TRUE),
    return_touchdown = sum(return_touchdown == 1, na.rm = TRUE),
    two_point_success = sum(two_point_success == 1, na.rm = TRUE),
    pass_touchdown = sum(pass_touchdown == 1, na.rm = TRUE),
    rush_touchdown = sum(rush_touchdown == 1, na.rm = TRUE),
    interception = sum(interception == 1, na.rm = TRUE),
    fumble_lost = sum(fumble_lost == 1, na.rm = TRUE),
    safety = sum(safety == 1, na.rm = TRUE)
  )
```

```{r retention}

# CREATE A TEAM DICT
team_abbr_map <- c(
  ARI = "ARI",
  ARZ = "ARI",
  ATL = "ATL",
  BAL = "BAL",
  BLT = "BAL",
  BUF = "BUF",
  CAR = "CAR",
  CHI = "CHI",
  CIN = "CIN",
  CLE = "CLE",
  CLV = "CLE",
  DAL = "DAL",
  DEN = "DEN",
  DET = "DET",
  GB  = "GB",
  HOU = "HOU",
  HST = "HOU",
  IND = "IND",
  JAX = "JAX",
  KC  = "KC",
  LA  = "LA",
  LAC = "LAC",
  LV  = "LV",
  MIA = "MIA",
  MIN = "MIN",
  NE  = "NE",
  NO  = "NO",
  NYG = "NYG",
  NYJ = "NYJ",
  OAK = "LV",
  PHI = "PHI",
  PIT = "PIT",
  SD  = "LAC",
  SEA = "SEA",
  SF  = "SF",
  SL  = "LA",
  TB  = "TB",
  TEN = "TEN",
  WAS = "WAS"
)

# LOAD ROSTERS
tmp <- load_rosters(seasons = 2003:2024)

# MAP TEAM ABBR
tmp <- tmp %>%
  mutate(team = recode(team, !!!team_abbr_map))

# DEFINE POS GROUPS
offensive_pos <- c('C', 'FB', 'G', 'OL', 'QB', 'RB', 'T', 'TE', 'WR') 
defensive_pos <- c('CB', 'DB', 'DE', 'DL', 'DT', 'FS', 'ILB', 'LB', 'MLB', 'NT', 'OLB', 'S', 'SS')
special_pos   <- c('LS', 'K', 'KR', 'P', 'PR')

# CREATE RETENTION TAG FOR DFS
retention_off_df <- tmp %>%
  filter(position %in% offensive_pos) %>%
  select(team, season, full_name) %>%
  mutate(prev_season = season - 1) %>%
  left_join(tmp %>%
              filter(position %in% offensive_pos) %>%
              select(team, season, full_name) %>%
              rename(prev_season = season,
                     prev_team = team),
            by = c("prev_season", "full_name")) %>%
  mutate(retained = team == prev_team)

retention_def_df <- tmp %>%
  filter(position %in% defensive_pos) %>%
  select(team, season, full_name) %>%
  mutate(prev_season = season - 1) %>%
  left_join(tmp %>%
              filter(position %in% defensive_pos) %>%
              select(team, season, full_name) %>%
              rename(prev_season = season,
                     prev_team = team),
            by = c("prev_season", "full_name")) %>%
  mutate(retained = team == prev_team)

retention_spec_df <- tmp %>%
  filter(position %in% special_pos) %>%
  select(team, season, full_name) %>%
  mutate(prev_season = season - 1) %>%
  left_join(tmp %>%
              filter(position %in% special_pos) %>%
              select(team, season, full_name) %>%
              rename(prev_season = season,
                     prev_team = team),
            by = c("prev_season", "full_name")) %>%
  mutate(retained = team == prev_team)

# GET COUNTS OF RETENTION
roster_retention_off <- retention_off_df %>%
  group_by(team, season) %>%
  summarize(offensive_retention = sum(retained, na.rm = TRUE), .groups = 'drop')

roster_retention_def <- retention_def_df %>%
  group_by(team, season) %>%
  summarize(defensive_retention = sum(retained, na.rm = TRUE), .groups = 'drop')

roster_retention_spec <- retention_spec_df %>%
  group_by(team, season) %>%
  summarize(special_retention = sum(retained, na.rm = TRUE), .groups = 'drop')

```


```{r merge_retention}
# MERGE RETENTION COUNTS
roster_retention <- merge(roster_retention_off, roster_retention_def, by=c('team', 'season'), all=TRUE)
roster_retention <- merge(roster_retention, roster_retention_spec, by=c('team', 'season'), all=TRUE)
```


```{r save_data}
data_summ <- merge(data_summ, roster_retention, by.x = c('posteam', 'season'), by.y = c('team', 'season'), all.x = TRUE)

write.csv(data_summ, "nfl_data.csv")

```


